// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVU3DDTbAWHJ7kdjIbB-sUr7-M7iiCN0',
    appId: '1:860780974282:web:effd9d00acaff6f720a433',
    messagingSenderId: '860780974282',
    projectId: 'pqcambui-41a18',
    authDomain: 'pqcambui-41a18.firebaseapp.com',
    databaseURL: 'https://pqcambui-41a18-default-rtdb.firebaseio.com',
    storageBucket: 'pqcambui-41a18.appspot.com',
    measurementId: 'G-ZJ2E0MMYL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAS3Q7SF9MNYYk9h8VHwMYwf8rJahEYrE',
    appId: '1:860780974282:android:3af57897d8ef04cd20a433',
    messagingSenderId: '860780974282',
    projectId: 'pqcambui-41a18',
    databaseURL: 'https://pqcambui-41a18-default-rtdb.firebaseio.com',
    storageBucket: 'pqcambui-41a18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFORlQDCFXIRfrnoUey56Cq3oNcql0y7w',
    appId: '1:860780974282:ios:01f6a7308d40e50820a433',
    messagingSenderId: '860780974282',
    projectId: 'pqcambui-41a18',
    databaseURL: 'https://pqcambui-41a18-default-rtdb.firebaseio.com',
    storageBucket: 'pqcambui-41a18.appspot.com',
    iosClientId: '860780974282-g1t84c65sdmv6mh1bapgv1noqssh48es.apps.googleusercontent.com',
    iosBundleId: 'com.example.parqueCambui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFORlQDCFXIRfrnoUey56Cq3oNcql0y7w',
    appId: '1:860780974282:ios:066e95241f0393ee20a433',
    messagingSenderId: '860780974282',
    projectId: 'pqcambui-41a18',
    databaseURL: 'https://pqcambui-41a18-default-rtdb.firebaseio.com',
    storageBucket: 'pqcambui-41a18.appspot.com',
    iosClientId: '860780974282-gbjaapi79fovvpsql85k05vh9jev51bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.parqueCambui.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiVU3DDTbAWHJ7kdjIbB-sUr7-M7iiCN0',
    appId: '1:860780974282:web:6d8a43d6c05fbbf120a433',
    messagingSenderId: '860780974282',
    projectId: 'pqcambui-41a18',
    authDomain: 'pqcambui-41a18.firebaseapp.com',
    databaseURL: 'https://pqcambui-41a18-default-rtdb.firebaseio.com',
    storageBucket: 'pqcambui-41a18.appspot.com',
    measurementId: 'G-1WY6YKM0QM',
  );
}
